import { Product } from "./types";

export const mockProducts: Product[] = [
  {
    id: "AGB-001",
    sku: "AGB-001",
    name: "Agarbatti Sandal",
    category: "Pooja Samagri",
    price: 35,
    costPrice: 25,
    unit: "Packet",
    stock: 50,
    status: "active",
    image:
      "https://images.unsplash.com/photo-1545239351-1141bd82e8a6?auto=format&fit=crop&w=400&q=80",
  },
  {
    id: "AGB-002",
    sku: "AGB-002",
    name: "Camphor",
    category: "Pooja Samagri",
    price: 20,
    costPrice: 12,
    unit: "Packet",
    stock: 30,
    status: "active",
  },
  {
    id: "HRC-002",
    sku: "HRC-002",
    name: "Harpic 500ml",
    category: "Cleaning Essentials",
    price: 90,
    costPrice: 70,
    unit: "Bottle",
    stock: 25,
    status: "active",
    image:
      "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=400&q=80",
  },
  {
    id: "PHL-003",
    sku: "PHL-003",
    name: "Phenyl White 1L",
    category: "Cleaning Essentials",
    price: 50,
    costPrice: 32,
    unit: "Bottle",
    stock: 20,
    status: "active",
  },
  {
    id: "VIM-004",
    sku: "VIM-004",
    name: "Vim Bar",
    category: "Cleaning Essentials",
    price: 10,
    costPrice: 6,
    unit: "Piece",
    stock: 100,
    status: "active",
  },
  {
    id: "BKT-003",
    sku: "BKT-003",
    name: "Bucket 10L",
    category: "Plastics & Dustbins",
    price: 150,
    costPrice: 110,
    unit: "Piece",
    stock: 12,
    status: "active",
  },
  {
    id: "DST-004",
    sku: "DST-004",
    name: "Dustbin Small",
    category: "Plastics & Dustbins",
    price: 120,
    costPrice: 85,
    unit: "Piece",
    stock: 15,
    status: "active",
  },
  {
    id: "PPC-005",
    sku: "PPC-005",
    name: "Paper Cups 100 pcs",
    category: "Disposable Items",
    price: 45,
    costPrice: 30,
    unit: "Pack",
    stock: 20,
    status: "active",
  },
  {
    id: "PPP-006",
    sku: "PPP-006",
    name: "Paper Plates 50 pcs",
    category: "Disposable Items",
    price: 35,
    costPrice: 22,
    unit: "Pack",
    stock: 25,
    status: "active",
  },
  {
    id: "SCR-007",
    sku: "SCR-007",
    name: "Steel Scrubber",
    category: "Kitchen Essentials",
    price: 10,
    costPrice: 6,
    unit: "Piece",
    stock: 80,
    status: "active",
  },
];
